# Generated by Django 2.0.7 on 2018-07-07 22:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_article', models.BooleanField(default=False)),
                ('is_space', models.BooleanField(default=False)),
                ('initial_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='initial date')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='end date')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'vigente'), (1, 'caducado'), (2, 'recibido'), (3, 'perdido')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='articles.Article')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_loans', to='users.RegisteredUser')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='articles.Space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='users.RegisteredUser')),
            ],
            options={
                'verbose_name': ('loan',),
                'verbose_name_plural': 'loans',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_article', models.BooleanField(default=False)),
                ('is_space', models.BooleanField(default=False)),
                ('initial_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='initial date')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='end date')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'pendiente'), (1, 'entregado'), (2, 'rechazado')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='articles.Article')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='articles.Space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.RegisteredUser')),
            ],
            options={
                'verbose_name': ('reservation',),
                'verbose_name_plural': 'reservations',
            },
        ),
    ]
