# Generated by Django 2.0.4 on 2018-04-27 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateTimeField(default=datetime.datetime(2018, 4, 27, 16, 44, 5, 337577), verbose_name='initial date')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2018, 4, 27, 16, 44, 5, 337577), verbose_name='end date')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateTimeField(default=datetime.datetime(2018, 4, 27, 16, 44, 5, 337577), verbose_name='initial date')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2018, 4, 27, 16, 44, 5, 337577), verbose_name='end date')),
                ('state', models.IntegerField(choices=[(0, 'pendiente'), (1, 'entregado'), (2, 'rechazado')], default=0)),
            ],
        ),
    ]
