# Generated by Django 2.0.3 on 2018-05-03 19:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('articles', '0005_auto_20180503_1928'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='article_or_space',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'vigente'), (1, 'caducado'), (2, 'recibido'), (3, 'perdido')], default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.RegisteredUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='article_or_space',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='articles.Space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.RegisteredUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='initial_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='initial date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='initial_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='initial date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pendiente'), (1, 'entregado'), (2, 'rechazado')], default=0),
        ),
    ]
