# Generated by Django 2.0.5 on 2018-05-09 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='articles.Space'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='articles.Space'),
        ),
    ]
