# Generated by Django 2.0.5 on 2018-05-08 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': ('loan',), 'verbose_name_plural': 'loans'},
        ),
    ]
