# Generated by Django 2.0.3 on 2018-05-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20180503_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='article_or_space',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='article_or_space',
            new_name='space',
        ),
    ]
