# Generated by Django 2.0.5 on 2018-05-03 20:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20180503_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='initial date')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='end date')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'vigente'), (1, 'caducado'), (2, 'recibido'), (3, 'perdido')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='initial date')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='end date')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'pendiente'), (1, 'entregado'), (2, 'rechazado')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='articleloan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='articleloan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='articleloan',
            name='initial_date',
        ),
        migrations.RemoveField(
            model_name='articleloan',
            name='state',
        ),
        migrations.RemoveField(
            model_name='articlereservation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='articlereservation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='articlereservation',
            name='initial_date',
        ),
        migrations.RemoveField(
            model_name='articlereservation',
            name='state',
        ),
        migrations.RemoveField(
            model_name='spaceloan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='spaceloan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='spaceloan',
            name='initial_date',
        ),
        migrations.RemoveField(
            model_name='spaceloan',
            name='state',
        ),
        migrations.RemoveField(
            model_name='spacereservation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='spacereservation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='spacereservation',
            name='initial_date',
        ),
        migrations.RemoveField(
            model_name='spacereservation',
            name='state',
        ),
        migrations.AddField(
            model_name='articleloan',
            name='loan_ptr',
            field=models.OneToOneField(auto_created=True, default='default', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.Loan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlereservation',
            name='reservation_ptr',
            field=models.OneToOneField(auto_created=True, default='default', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.Reservation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spaceloan',
            name='loan_ptr',
            field=models.OneToOneField(auto_created=True, default='default', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.Loan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spacereservation',
            name='reservation_ptr',
            field=models.OneToOneField(auto_created=True, default='default', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.Reservation'),
            preserve_default=False,
        ),
    ]
