# Generated by Django 2.0.5 on 2018-05-04 00:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20180503_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleloan',
            name='loan_ptr',
        ),
        migrations.RemoveField(
            model_name='articlereservation',
            name='reservation_ptr',
        ),
        migrations.RemoveField(
            model_name='spaceloan',
            name='loan_ptr',
        ),
        migrations.RemoveField(
            model_name='spacereservation',
            name='reservation_ptr',
        ),
        migrations.AddField(
            model_name='articleloan',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='articleloan',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleloan',
            name='initial_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='initial date'),
        ),
        migrations.AddField(
            model_name='articleloan',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'vigente'), (1, 'caducado'), (2, 'recibido'), (3, 'perdido')], default=0),
        ),
        migrations.AddField(
            model_name='articlereservation',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='articlereservation',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlereservation',
            name='initial_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='initial date'),
        ),
        migrations.AddField(
            model_name='articlereservation',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pendiente'), (1, 'entregado'), (2, 'rechazado')], default=0),
        ),
        migrations.AddField(
            model_name='spaceloan',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='spaceloan',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spaceloan',
            name='initial_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='initial date'),
        ),
        migrations.AddField(
            model_name='spaceloan',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'vigente'), (1, 'caducado'), (2, 'recibido'), (3, 'perdido')], default=0),
        ),
        migrations.AddField(
            model_name='spacereservation',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='spacereservation',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spacereservation',
            name='initial_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='initial date'),
        ),
        migrations.AddField(
            model_name='spacereservation',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pendiente'), (1, 'entregado'), (2, 'rechazado')], default=0),
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
