# Generated by Django 2.0.5 on 2018-07-04 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20180704_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_loans', to='users.RegisteredUser'),
        ),
    ]
