# Generated by Django 2.0.3 on 2018-07-04 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20180704_1922'),
        ('reservations', '0002_auto_20180531_1828'),
    ]

    operations = [
    ]
