# Generated by Django 2.0.4 on 2018-04-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.BinaryField()),
                ('description', models.TextField()),
                ('status', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
