# Generated by Django 2.0.3 on 2018-05-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Disponible'), (1, 'En préstamo'), (2, 'En reparación'), (3, 'Perdido')], default=0),
        ),
    ]
