# Generated by Django 2.0.3 on 2018-05-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180427_1644'),
        ('articles', '0003_auto_20180503_1355'),
    ]

    operations = [
    ]
