# Generated by Django 2.0.3 on 2018-05-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_merge_20180503_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Disponible'), (1, 'En préstamo'), (2, 'En reparación')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Disponible'), (1, 'En préstamo'), (2, 'En reparación'), (3, 'Perdido')], default=0),
        ),
    ]
