# Generated by Django 2.0.3 on 2018-05-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180503_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='articles/images/items/', upload_to=''),
        ),
    ]
