# Generated by Django 2.0.5 on 2018-07-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='avatar',
            field=models.ImageField(default='users/images/default-profile.png', upload_to='users/avatar'),
        ),
    ]
