# Generated by Django 2.0.3 on 2018-05-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180503_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='RUT',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='can_reserve',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='email',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='avatar',
            field=models.ImageField(default='/static/users/images/default-profile.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Préstamos y Reservas'), (1, 'Sólo préstamos'), (2, 'Sólo reservas'), (3, 'Nada')], default=0),
        ),
    ]
