# Generated by Django 2.0.4 on 2018-05-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180503_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='avatar',
            field=models.ImageField(default='users/images/default-profile.png', upload_to=''),
        ),
    ]
